# Generated by Django 5.2.1 on 2025-06-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0002_alter_ad_annual_condominium_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="zip_code",
            field=models.IntegerField(null=True),
        ),
    ]
