# Generated by Django 5.2.1 on 2025-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0003_alter_ad_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="dept_code",
            field=models.IntegerField(null=True),
        ),
    ]
