# Generated by Django 5.2.1 on 2025-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField()),
                ("dept_code", models.IntegerField()),
                ("zip_code", models.IntegerField()),
                ("city", models.CharField()),
                ("annual_condominium_fees", models.IntegerField()),
            ],
        ),
    ]
